#!/bin/bash

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function update_profile {
  echo "Update Profile"
  cp "${DIR}"/bashrc_extended ~/.bashrc_extended
  cp "${DIR}"/bash_aliases ~/.bash_aliases
  cp "${DIR}"/inputrc ~/.inputrc
  cp "${DIR}"/gitconfig ~/.gitconfig
}

function install_vimplugins {
  echo "Install VIM Plugins"
  cp ${DIR}/vimrc.local.plugins ~/.vimrc.local.plugins
  cp ${DIR}/vimrc.local.before ~/.vimrc.local.before
  cp ${DIR}/vimrc.local ~/.vimrc.local
  [ ! -e ~/.vim/bin/install ] && curl vimfiles.luan.sh/install | bash
  ~/.vim/update
}

function install_cli {
  echo "Install CLI"
  if [ ! -e /usr/local/bin/credhub ]; then
    curl -LO "https://github.com/cloudfoundry-incubator/credhub-cli/releases/download/1.2.0/credhub-linux-1.2.0.tgz"
    tar -zxvf "credhub-linux-1.2.0.tgz"
    rm "credhub-linux-1.2.0.tgz"
    sudo mv "credhub" "/usr/local/bin"
    chmod +x "/usr/local/bin/credhub"
  fi

  if [ ! -e /usr/local/bin/bosh ]; then
    curl -LO "https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-2.0.28-linux-amd64"
    sudo mv "bosh-cli-2.0.28-linux-amd64" "/usr/local/bin/bosh"
    chmod +x "/usr/local/bin/bosh"
  fi

}

function install_apt {
  echo "Install APT"
  sudo apt-get install curl direnv neovim python3-neovim python3 python3-pip -y
}

function install_go {
  echo "Install Go"
  if [ ! -e /usr/local/go ]; then
    curl -LO "https://storage.googleapis.com/golang/go1.9.1.linux-amd64.tar.gz"
    tar -xvf "go1.9.1.linux-amd64.tar.gz"
    sudo mv go /usr/local/
  fi
}

function install_git_prompt {
  echo "Install Git Prompt"
  if [ ! -d ~/.bash-git-prompt ]; then
    git clone https://github.com/magicmonty/bash-git-prompt.git ~/.bash-git-prompt --depth=1
  fi
}

function main {
  install_apt
  curl -s "https://get.sdkman.io" | bash
  update_profile
  install_go
  install_vimplugins
  install_cli
  install_git_prompt
}

main

